---
# This playbook deploys the whole application stack in this site.
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  
  tasks:
  - name: check the china-mobile-gateway
    icmp_ping: host="117.144.54.25"
    ignore_errors: true
    register: result
  - include_tasks: report_weixin.yml
    vars:
        ip: "117.144.54.25"
        time: "{{ lookup('pipe', 'date -d \"1 day ago\" +\"%Y%m%d\"') }}"
        info:  "connect failed"
        err:   "{{result}}"
    when: result|failed
