---
# This playbook contains common plays that will be run on all nodes.
- name: Download pptpd_1.4.0-7_amd64.deb
  get_url:
    url: http://archive.ubuntu.com/ubuntu/pool/main/p/pptpd/pptpd_1.4.0-7_amd64.deb
    dest: /root/pptpd_1.4.0-7_amd64.deb

- name: install pptpd_1.4.0-7_amd64.deb
  shell: dpkg -i pptpd_1.4.0-7_amd64.deb
  ignore_errors: yes

- name: add localip to pptpd.config 
  shell: echo "localip 10.99.99.1" >> /etc/pptpd.config
  ignore_errors: yes

- name: add  remoteip to pptpd.config
  shell: echo "remoteip 10.99.99.100-200" >> /etc/pptpd.config
  ignore_errors: yes

- name: add  dns to options.pptpd
  shell: echo "ms-dns 8.8.8.8" >> /etc/ppp/options.pptpd
  ignore_errors: yes

- name: add  dns to options.pptpd
  shell: echo "ms-dns 8.8.4.4" >> /etc/ppp/options.pptpd
  ignore_errors: yes

- name: add  ipv4 to kernal
  shell: echo "net.ipv4.ip_forward=1" >>/etc/sysctl.conf 
  ignore_errors: yes


- name:  change the ipv4 in time 
  shell:  sysctl -p
  ignore_errors: yes

- name:  add user0 and password to chap-secrets
  shell:  echo "sinobot         pptpd   123456              *"  >> /etc/ppp/chap-secrets
  ignore_errors: yes

- name:  add user1 and password to chap-secrets
  shell:  echo "sinobot1         pptpd   123456              *"  >> /etc/ppp/chap-secrets
  ignore_errors: yes

- name:  add user2 and password to chap-secrets
  shell:  echo "sinobot2         pptpd   123456              *"  >> /etc/ppp/chap-secrets
  ignore_errors: yes


- name: iptable-save
  shell:  iptables -t nat -A POSTROUTING -s 10.99.99.0/24 -o eth0 -j MASQUERADE
  ignore_errors: yes

- name: Install iptables-persistent
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - iptables-persistent


- name:  change the ipv4 in time
  shell:  /etc/init.d/./iptables-persistent  save
  ignore_errors: yes

- name: start service of pptpd
  shell: /etc/init.d/pptpd restart
  ignore_errors: yes
